baseURL: https://localhost/
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en: 
    title: Careful! Messy notes ahead.
    languageName: English
    contentDir: content/english
    weight: 2
    menu:
        nav:
          - name: Home
            url: /en
            weight: 1
          - name: Blog
            url: /en/post/
            weight: 2
          - name: Tags
            url: /en/tags/
            weight: 3
          - name: About
            url: /en/about/
            weight: 4
          - name: RSS
            url: /en/index.xml
            weight: 5
  fr: 
    params:
      description: Voici mes notes sur tout ce que j'aime lore, écouter et ecrire.. My writing is _pour_ but this is for myself. Enjoy !
      homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
      footer: Généré avec [Hugo](https://gohugo.io/). Utilise le thème [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
      navigation:
        help: Aide
    title: Danger ! Plein de mots en désordre droit devant.
    languageName: Français
    contentDir: content/french
    weight: 1
    menu:
        nav:
          - name: Accueil
            url: /fr
            weight: 1
          - name: Blog
            url: /fr/post/
            weight: 2
          - name: Tags
            url: /fr/tags/
            weight: 3
          - name: A propos
            url: /fr/about/
            weight: 4
          - name: RSS
            url: /fr/index.xml
            weight: 5
title: Careful! Mess ahead!
theme: cupper-hugo-theme
# googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: This is my notes from anything that I love to read, to listen and to write about. My writing is _pour_ but this is for myself. Enjoy !
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
    # avTitleText: My notes
  logoAlt: Personal notes logo image
    #customCss:
    #  - css/custom_01.css
    #  - css/custom_02.css
    #customJs:
    #  - js/custom_01.js
    #  - js/custom_02.js
  utterances:
    repo: username/username.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - identifier: home_menu
      name: Home
      url: /
      weight: 1
    - identifier: blog_menu
      name: Blog
      url: /post/
      weight: 2
    - identifier: tags_menu
      name: Tags
      url: /tags/
      weight: 3
    - identifier: about_menu
      name: About
      url: /about/
      weight: 4
    - identifier: rss_menu
      name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
